---
title: "Homework Class06"
author: "Gabriella Tanoto (A18024184)"
format: pdf
toc: true
---

# Question 6:

ORIGINAL CODE--

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
str(s1)
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA") #changed s1 to s3!

s1.b <- s1.chainA$atom$b
str(s1)
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")

```

>Q: How would you generalize the original code above to work with any set of input protein structures?

```{r}
graph.cA.aB <- function(x) {
  x.chainA <- trim.pdb(x, chain="A", elety="CA")
  x.b <- x.chainA$atom$b
  plotb3(x.b, sse=x.chainA, typ="l", ylab="Bfactor")
}

```

I just made the s1, s2, s3 into one factor, x, that is variable according to what is inputted into the function. 

```{r}
graph.cA.aB(s1)
```
```{r}
graph.cA.aB(s2)
```
```{r}
graph.cA.aB(s3)
```


